# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest.models.bucket import Bucket
from rest import util

from rest.models.bucket import Bucket  # noqa: E501

class BucketList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, buckets=None):  # noqa: E501
        """BucketList - a model defined in OpenAPI

        :param buckets: The buckets of this BucketList.  # noqa: E501
        :type buckets: List[Bucket]
        """
        self.openapi_types = {
            'buckets': List[Bucket]
        }

        self.attribute_map = {
            'buckets': 'buckets'
        }

        self._buckets = buckets

    @classmethod
    def from_dict(cls, dikt) -> 'BucketList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BucketList of this BucketList.  # noqa: E501
        :rtype: BucketList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def buckets(self):
        """Gets the buckets of this BucketList.


        :return: The buckets of this BucketList.
        :rtype: List[Bucket]
        """
        return self._buckets

    @buckets.setter
    def buckets(self, buckets):
        """Sets the buckets of this BucketList.


        :param buckets: The buckets of this BucketList.
        :type buckets: List[Bucket]
        """

        self._buckets = buckets
