# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest import util


class ClusterComposite(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, tenants=None):  # noqa: E501
        """ClusterComposite - a model defined in OpenAPI

        :param tenants: The tenants of this ClusterComposite.  # noqa: E501
        :type tenants: List[str]
        """
        self.openapi_types = {
            'tenants': List[str]
        }

        self.attribute_map = {
            'tenants': 'tenants'
        }

        self._tenants = tenants

    @classmethod
    def from_dict(cls, dikt) -> 'ClusterComposite':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClusterComposite of this ClusterComposite.  # noqa: E501
        :rtype: ClusterComposite
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tenants(self):
        """Gets the tenants of this ClusterComposite.


        :return: The tenants of this ClusterComposite.
        :rtype: List[str]
        """
        return self._tenants

    @tenants.setter
    def tenants(self, tenants):
        """Sets the tenants of this ClusterComposite.


        :param tenants: The tenants of this ClusterComposite.
        :type tenants: List[str]
        """

        self._tenants = tenants
