# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest.models.cluster_state import ClusterState
from rest import util

from rest.models.cluster_state import ClusterState  # noqa: E501

class ClusterStateResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, state=None):  # noqa: E501
        """ClusterStateResponse - a model defined in OpenAPI

        :param state: The state of this ClusterStateResponse.  # noqa: E501
        :type state: ClusterState
        """
        self.openapi_types = {
            'state': ClusterState
        }

        self.attribute_map = {
            'state': 'state'
        }

        self._state = state

    @classmethod
    def from_dict(cls, dikt) -> 'ClusterStateResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClusterStateResponse of this ClusterStateResponse.  # noqa: E501
        :rtype: ClusterStateResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self):
        """Gets the state of this ClusterStateResponse.


        :return: The state of this ClusterStateResponse.
        :rtype: ClusterState
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this ClusterStateResponse.


        :param state: The state of this ClusterStateResponse.
        :type state: ClusterState
        """

        self._state = state
