# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest.models.virtual_ip import VirtualIp
from rest import util

from rest.models.virtual_ip import VirtualIp  # noqa: E501

class ClusterControlplane(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, vip=None):  # noqa: E501
        """ClusterControlplane - a model defined in OpenAPI

        :param vip: The vip of this ClusterControlplane.  # noqa: E501
        :type vip: VirtualIp
        """
        self.openapi_types = {
            'vip': VirtualIp
        }

        self.attribute_map = {
            'vip': 'vip'
        }

        self._vip = vip

    @classmethod
    def from_dict(cls, dikt) -> 'ClusterControlplane':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClusterControlplane of this ClusterControlplane.  # noqa: E501
        :rtype: ClusterControlplane
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vip(self):
        """Gets the vip of this ClusterControlplane.


        :return: The vip of this ClusterControlplane.
        :rtype: VirtualIp
        """
        return self._vip

    @vip.setter
    def vip(self, vip):
        """Sets the vip of this ClusterControlplane.


        :param vip: The vip of this ClusterControlplane.
        :type vip: VirtualIp
        """

        self._vip = vip
