# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest import util


class ClusterFlavor(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    UNKNOWN = "CF_UNKNOWN"
    BOH = "CF_BOH"
    K8S = "CF_K8S"
    def __init__(self):  # noqa: E501
        """ClusterFlavor - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ClusterFlavor':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClusterFlavor of this ClusterFlavor.  # noqa: E501
        :rtype: ClusterFlavor
        """
        return util.deserialize_model(dikt, cls)
