# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest import util


class ClusterNetwork(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, network_id=None, cidr=None, domain=None, gateway_id=None, gateway_ip=None, secondary_gateway_id=None, secondary_gateway_ip=None, default_route_ip=None, primary_public_ip=None, secondary_public_ip=None, endpoint_ip=None):  # noqa: E501
        """ClusterNetwork - a model defined in OpenAPI

        :param network_id: The network_id of this ClusterNetwork.  # noqa: E501
        :type network_id: str
        :param cidr: The cidr of this ClusterNetwork.  # noqa: E501
        :type cidr: str
        :param domain: The domain of this ClusterNetwork.  # noqa: E501
        :type domain: str
        :param gateway_id: The gateway_id of this ClusterNetwork.  # noqa: E501
        :type gateway_id: str
        :param gateway_ip: The gateway_ip of this ClusterNetwork.  # noqa: E501
        :type gateway_ip: str
        :param secondary_gateway_id: The secondary_gateway_id of this ClusterNetwork.  # noqa: E501
        :type secondary_gateway_id: str
        :param secondary_gateway_ip: The secondary_gateway_ip of this ClusterNetwork.  # noqa: E501
        :type secondary_gateway_ip: str
        :param default_route_ip: The default_route_ip of this ClusterNetwork.  # noqa: E501
        :type default_route_ip: str
        :param primary_public_ip: The primary_public_ip of this ClusterNetwork.  # noqa: E501
        :type primary_public_ip: str
        :param secondary_public_ip: The secondary_public_ip of this ClusterNetwork.  # noqa: E501
        :type secondary_public_ip: str
        :param endpoint_ip: The endpoint_ip of this ClusterNetwork.  # noqa: E501
        :type endpoint_ip: str
        """
        self.openapi_types = {
            'network_id': str,
            'cidr': str,
            'domain': str,
            'gateway_id': str,
            'gateway_ip': str,
            'secondary_gateway_id': str,
            'secondary_gateway_ip': str,
            'default_route_ip': str,
            'primary_public_ip': str,
            'secondary_public_ip': str,
            'endpoint_ip': str
        }

        self.attribute_map = {
            'network_id': 'networkId',
            'cidr': 'cidr',
            'domain': 'domain',
            'gateway_id': 'gatewayId',
            'gateway_ip': 'gatewayIp',
            'secondary_gateway_id': 'secondaryGatewayId',
            'secondary_gateway_ip': 'secondaryGatewayIp',
            'default_route_ip': 'defaultRouteIp',
            'primary_public_ip': 'primaryPublicIp',
            'secondary_public_ip': 'secondaryPublicIp',
            'endpoint_ip': 'endpointIp'
        }

        self._network_id = network_id
        self._cidr = cidr
        self._domain = domain
        self._gateway_id = gateway_id
        self._gateway_ip = gateway_ip
        self._secondary_gateway_id = secondary_gateway_id
        self._secondary_gateway_ip = secondary_gateway_ip
        self._default_route_ip = default_route_ip
        self._primary_public_ip = primary_public_ip
        self._secondary_public_ip = secondary_public_ip
        self._endpoint_ip = endpoint_ip

    @classmethod
    def from_dict(cls, dikt) -> 'ClusterNetwork':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClusterNetwork of this ClusterNetwork.  # noqa: E501
        :rtype: ClusterNetwork
        """
        return util.deserialize_model(dikt, cls)

    @property
    def network_id(self):
        """Gets the network_id of this ClusterNetwork.


        :return: The network_id of this ClusterNetwork.
        :rtype: str
        """
        return self._network_id

    @network_id.setter
    def network_id(self, network_id):
        """Sets the network_id of this ClusterNetwork.


        :param network_id: The network_id of this ClusterNetwork.
        :type network_id: str
        """

        self._network_id = network_id

    @property
    def cidr(self):
        """Gets the cidr of this ClusterNetwork.


        :return: The cidr of this ClusterNetwork.
        :rtype: str
        """
        return self._cidr

    @cidr.setter
    def cidr(self, cidr):
        """Sets the cidr of this ClusterNetwork.


        :param cidr: The cidr of this ClusterNetwork.
        :type cidr: str
        """

        self._cidr = cidr

    @property
    def domain(self):
        """Gets the domain of this ClusterNetwork.


        :return: The domain of this ClusterNetwork.
        :rtype: str
        """
        return self._domain

    @domain.setter
    def domain(self, domain):
        """Sets the domain of this ClusterNetwork.


        :param domain: The domain of this ClusterNetwork.
        :type domain: str
        """

        self._domain = domain

    @property
    def gateway_id(self):
        """Gets the gateway_id of this ClusterNetwork.


        :return: The gateway_id of this ClusterNetwork.
        :rtype: str
        """
        return self._gateway_id

    @gateway_id.setter
    def gateway_id(self, gateway_id):
        """Sets the gateway_id of this ClusterNetwork.


        :param gateway_id: The gateway_id of this ClusterNetwork.
        :type gateway_id: str
        """

        self._gateway_id = gateway_id

    @property
    def gateway_ip(self):
        """Gets the gateway_ip of this ClusterNetwork.


        :return: The gateway_ip of this ClusterNetwork.
        :rtype: str
        """
        return self._gateway_ip

    @gateway_ip.setter
    def gateway_ip(self, gateway_ip):
        """Sets the gateway_ip of this ClusterNetwork.


        :param gateway_ip: The gateway_ip of this ClusterNetwork.
        :type gateway_ip: str
        """

        self._gateway_ip = gateway_ip

    @property
    def secondary_gateway_id(self):
        """Gets the secondary_gateway_id of this ClusterNetwork.


        :return: The secondary_gateway_id of this ClusterNetwork.
        :rtype: str
        """
        return self._secondary_gateway_id

    @secondary_gateway_id.setter
    def secondary_gateway_id(self, secondary_gateway_id):
        """Sets the secondary_gateway_id of this ClusterNetwork.


        :param secondary_gateway_id: The secondary_gateway_id of this ClusterNetwork.
        :type secondary_gateway_id: str
        """

        self._secondary_gateway_id = secondary_gateway_id

    @property
    def secondary_gateway_ip(self):
        """Gets the secondary_gateway_ip of this ClusterNetwork.


        :return: The secondary_gateway_ip of this ClusterNetwork.
        :rtype: str
        """
        return self._secondary_gateway_ip

    @secondary_gateway_ip.setter
    def secondary_gateway_ip(self, secondary_gateway_ip):
        """Sets the secondary_gateway_ip of this ClusterNetwork.


        :param secondary_gateway_ip: The secondary_gateway_ip of this ClusterNetwork.
        :type secondary_gateway_ip: str
        """

        self._secondary_gateway_ip = secondary_gateway_ip

    @property
    def default_route_ip(self):
        """Gets the default_route_ip of this ClusterNetwork.


        :return: The default_route_ip of this ClusterNetwork.
        :rtype: str
        """
        return self._default_route_ip

    @default_route_ip.setter
    def default_route_ip(self, default_route_ip):
        """Sets the default_route_ip of this ClusterNetwork.


        :param default_route_ip: The default_route_ip of this ClusterNetwork.
        :type default_route_ip: str
        """

        self._default_route_ip = default_route_ip

    @property
    def primary_public_ip(self):
        """Gets the primary_public_ip of this ClusterNetwork.


        :return: The primary_public_ip of this ClusterNetwork.
        :rtype: str
        """
        return self._primary_public_ip

    @primary_public_ip.setter
    def primary_public_ip(self, primary_public_ip):
        """Sets the primary_public_ip of this ClusterNetwork.


        :param primary_public_ip: The primary_public_ip of this ClusterNetwork.
        :type primary_public_ip: str
        """

        self._primary_public_ip = primary_public_ip

    @property
    def secondary_public_ip(self):
        """Gets the secondary_public_ip of this ClusterNetwork.


        :return: The secondary_public_ip of this ClusterNetwork.
        :rtype: str
        """
        return self._secondary_public_ip

    @secondary_public_ip.setter
    def secondary_public_ip(self, secondary_public_ip):
        """Sets the secondary_public_ip of this ClusterNetwork.


        :param secondary_public_ip: The secondary_public_ip of this ClusterNetwork.
        :type secondary_public_ip: str
        """

        self._secondary_public_ip = secondary_public_ip

    @property
    def endpoint_ip(self):
        """Gets the endpoint_ip of this ClusterNetwork.


        :return: The endpoint_ip of this ClusterNetwork.
        :rtype: str
        """
        return self._endpoint_ip

    @endpoint_ip.setter
    def endpoint_ip(self, endpoint_ip):
        """Sets the endpoint_ip of this ClusterNetwork.


        :param endpoint_ip: The endpoint_ip of this ClusterNetwork.
        :type endpoint_ip: str
        """

        self._endpoint_ip = endpoint_ip
