# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest import util


class ClusterState(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    UNKNOWN = "CS_UNKNOWN"
    NOMINAL = "CS_NOMINAL"
    DEGRADED = "CS_DEGRADED"
    STOPPED = "CS_STOPPED"
    INITIALIZING = "CS_INITIALIZING"
    CREATED = "CS_CREATED"
    CREATING = "CS_CREATING"
    ERROR = "CS_ERROR"
    REMOVED = "CS_REMOVED"
    STOPPING = "CS_STOPPING"
    STARTING = "CS_STARTING"
    def __init__(self):  # noqa: E501
        """ClusterState - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ClusterState':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClusterState of this ClusterState.  # noqa: E501
        :rtype: ClusterState
        """
        return util.deserialize_model(dikt, cls)
