# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest.models.host import Host
from rest import util

from rest.models.host import Host  # noqa: E501

class ClusterNodeListResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, nodes=None):  # noqa: E501
        """ClusterNodeListResponse - a model defined in OpenAPI

        :param nodes: The nodes of this ClusterNodeListResponse.  # noqa: E501
        :type nodes: List[Host]
        """
        self.openapi_types = {
            'nodes': List[Host]
        }

        self.attribute_map = {
            'nodes': 'nodes'
        }

        self._nodes = nodes

    @classmethod
    def from_dict(cls, dikt) -> 'ClusterNodeListResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClusterNodeListResponse of this ClusterNodeListResponse.  # noqa: E501
        :rtype: ClusterNodeListResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nodes(self):
        """Gets the nodes of this ClusterNodeListResponse.


        :return: The nodes of this ClusterNodeListResponse.
        :rtype: List[Host]
        """
        return self._nodes

    @nodes.setter
    def nodes(self, nodes):
        """Sets the nodes of this ClusterNodeListResponse.


        :param nodes: The nodes of this ClusterNodeListResponse.
        :type nodes: List[Host]
        """

        self._nodes = nodes
