# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest.models.feature_response import FeatureResponse
from rest import util

from rest.models.feature_response import FeatureResponse  # noqa: E501

class FeatureListResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, features=None):  # noqa: E501
        """FeatureListResponse - a model defined in OpenAPI

        :param features: The features of this FeatureListResponse.  # noqa: E501
        :type features: List[FeatureResponse]
        """
        self.openapi_types = {
            'features': List[FeatureResponse]
        }

        self.attribute_map = {
            'features': 'features'
        }

        self._features = features

    @classmethod
    def from_dict(cls, dikt) -> 'FeatureListResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FeatureListResponse of this FeatureListResponse.  # noqa: E501
        :rtype: FeatureListResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def features(self):
        """Gets the features of this FeatureListResponse.


        :return: The features of this FeatureListResponse.
        :rtype: List[FeatureResponse]
        """
        return self._features

    @features.setter
    def features(self, features):
        """Sets the features of this FeatureListResponse.


        :param features: The features of this FeatureListResponse.
        :type features: List[FeatureResponse]
        """

        self._features = features
