# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest.models.host import Host
from rest import util

from rest.models.host import Host  # noqa: E501

class HostList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, hosts=None):  # noqa: E501
        """HostList - a model defined in OpenAPI

        :param hosts: The hosts of this HostList.  # noqa: E501
        :type hosts: List[Host]
        """
        self.openapi_types = {
            'hosts': List[Host]
        }

        self.attribute_map = {
            'hosts': 'hosts'
        }

        self._hosts = hosts

    @classmethod
    def from_dict(cls, dikt) -> 'HostList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HostList of this HostList.  # noqa: E501
        :rtype: HostList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def hosts(self):
        """Gets the hosts of this HostList.


        :return: The hosts of this HostList.
        :rtype: List[Host]
        """
        return self._hosts

    @hosts.setter
    def hosts(self, hosts):
        """Sets the hosts of this HostList.


        :param hosts: The hosts of this HostList.
        :type hosts: List[Host]
        """

        self._hosts = hosts
