# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest.models.image import Image
from rest import util

from rest.models.image import Image  # noqa: E501

class ImageList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, images=None):  # noqa: E501
        """ImageList - a model defined in OpenAPI

        :param images: The images of this ImageList.  # noqa: E501
        :type images: List[Image]
        """
        self.openapi_types = {
            'images': List[Image]
        }

        self.attribute_map = {
            'images': 'images'
        }

        self._images = images

    @classmethod
    def from_dict(cls, dikt) -> 'ImageList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ImageList of this ImageList.  # noqa: E501
        :rtype: ImageList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def images(self):
        """Gets the images of this ImageList.


        :return: The images of this ImageList.
        :rtype: List[Image]
        """
        return self._images

    @images.setter
    def images(self, images):
        """Sets the images of this ImageList.


        :param images: The images of this ImageList.
        :type images: List[Image]
        """

        self._images = images
