# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest import util


class JobDefinition(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, uuid=None, info=None):  # noqa: E501
        """JobDefinition - a model defined in OpenAPI

        :param uuid: The uuid of this JobDefinition.  # noqa: E501
        :type uuid: str
        :param info: The info of this JobDefinition.  # noqa: E501
        :type info: str
        """
        self.openapi_types = {
            'uuid': str,
            'info': str
        }

        self.attribute_map = {
            'uuid': 'uuid',
            'info': 'info'
        }

        self._uuid = uuid
        self._info = info

    @classmethod
    def from_dict(cls, dikt) -> 'JobDefinition':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The JobDefinition of this JobDefinition.  # noqa: E501
        :rtype: JobDefinition
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uuid(self):
        """Gets the uuid of this JobDefinition.


        :return: The uuid of this JobDefinition.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this JobDefinition.


        :param uuid: The uuid of this JobDefinition.
        :type uuid: str
        """

        self._uuid = uuid

    @property
    def info(self):
        """Gets the info of this JobDefinition.


        :return: The info of this JobDefinition.
        :rtype: str
        """
        return self._info

    @info.setter
    def info(self, info):
        """Sets the info of this JobDefinition.


        :param info: The info of this JobDefinition.
        :type info: str
        """

        self._info = info
