# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest.models.job_definition import JobDefinition
from rest import util

from rest.models.job_definition import JobDefinition  # noqa: E501

class JobList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, list=None):  # noqa: E501
        """JobList - a model defined in OpenAPI

        :param list: The list of this JobList.  # noqa: E501
        :type list: List[JobDefinition]
        """
        self.openapi_types = {
            'list': List[JobDefinition]
        }

        self.attribute_map = {
            'list': 'list'
        }

        self._list = list

    @classmethod
    def from_dict(cls, dikt) -> 'JobList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The JobList of this JobList.  # noqa: E501
        :rtype: JobList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def list(self):
        """Gets the list of this JobList.


        :return: The list of this JobList.
        :rtype: List[JobDefinition]
        """
        return self._list

    @list.setter
    def list(self, list):
        """Sets the list of this JobList.


        :param list: The list of this JobList.
        :type list: List[JobDefinition]
        """

        self._list = list
