# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest.models.network import Network
from rest import util

from rest.models.network import Network  # noqa: E501

class NetworkList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, networks=None):  # noqa: E501
        """NetworkList - a model defined in OpenAPI

        :param networks: The networks of this NetworkList.  # noqa: E501
        :type networks: List[Network]
        """
        self.openapi_types = {
            'networks': List[Network]
        }

        self.attribute_map = {
            'networks': 'networks'
        }

        self._networks = networks

    @classmethod
    def from_dict(cls, dikt) -> 'NetworkList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NetworkList of this NetworkList.  # noqa: E501
        :rtype: NetworkList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def networks(self):
        """Gets the networks of this NetworkList.


        :return: The networks of this NetworkList.
        :rtype: List[Network]
        """
        return self._networks

    @networks.setter
    def networks(self, networks):
        """Sets the networks of this NetworkList.


        :param networks: The networks of this NetworkList.
        :type networks: List[Network]
        """

        self._networks = networks
