# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest.models.public_ip_response import PublicIPResponse
from rest import util

from rest.models.public_ip_response import PublicIPResponse  # noqa: E501

class PublicIPListResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, public_ips=None):  # noqa: E501
        """PublicIPListResponse - a model defined in OpenAPI

        :param public_ips: The public_ips of this PublicIPListResponse.  # noqa: E501
        :type public_ips: List[PublicIPResponse]
        """
        self.openapi_types = {
            'public_ips': List[PublicIPResponse]
        }

        self.attribute_map = {
            'public_ips': 'publicIps'
        }

        self._public_ips = public_ips

    @classmethod
    def from_dict(cls, dikt) -> 'PublicIPListResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PublicIPListResponse of this PublicIPListResponse.  # noqa: E501
        :rtype: PublicIPListResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def public_ips(self):
        """Gets the public_ips of this PublicIPListResponse.


        :return: The public_ips of this PublicIPListResponse.
        :rtype: List[PublicIPResponse]
        """
        return self._public_ips

    @public_ips.setter
    def public_ips(self, public_ips):
        """Sets the public_ips of this PublicIPListResponse.


        :param public_ips: The public_ips of this PublicIPListResponse.
        :type public_ips: List[PublicIPResponse]
        """

        self._public_ips = public_ips
