# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest import util


class Reference(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, tenant_id=None, id=None, name=None):  # noqa: E501
        """Reference - a model defined in OpenAPI

        :param tenant_id: The tenant_id of this Reference.  # noqa: E501
        :type tenant_id: str
        :param id: The id of this Reference.  # noqa: E501
        :type id: str
        :param name: The name of this Reference.  # noqa: E501
        :type name: str
        """
        self.openapi_types = {
            'tenant_id': str,
            'id': str,
            'name': str
        }

        self.attribute_map = {
            'tenant_id': 'tenantId',
            'id': 'id',
            'name': 'name'
        }

        self._tenant_id = tenant_id
        self._id = id
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'Reference':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Reference of this Reference.  # noqa: E501
        :rtype: Reference
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tenant_id(self):
        """Gets the tenant_id of this Reference.


        :return: The tenant_id of this Reference.
        :rtype: str
        """
        return self._tenant_id

    @tenant_id.setter
    def tenant_id(self, tenant_id):
        """Sets the tenant_id of this Reference.


        :param tenant_id: The tenant_id of this Reference.
        :type tenant_id: str
        """

        self._tenant_id = tenant_id

    @property
    def id(self):
        """Gets the id of this Reference.


        :return: The id of this Reference.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Reference.


        :param id: The id of this Reference.
        :type id: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Reference.


        :return: The name of this Reference.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Reference.


        :param name: The name of this Reference.
        :type name: str
        """

        self._name = name
