# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest import util


class SecurityGroupState(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    ALL = "SGS_ALL"
    ENABLED = "SGS_ENABLED"
    DISABLED = "SGS_DISABLED"
    def __init__(self):  # noqa: E501
        """SecurityGroupState - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'SecurityGroupState':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SecurityGroupState of this SecurityGroupState.  # noqa: E501
        :rtype: SecurityGroupState
        """
        return util.deserialize_model(dikt, cls)
