# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest.models.security_group_response import SecurityGroupResponse
from rest import util

from rest.models.security_group_response import SecurityGroupResponse  # noqa: E501

class SecurityGroupListResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, security_groups=None):  # noqa: E501
        """SecurityGroupListResponse - a model defined in OpenAPI

        :param security_groups: The security_groups of this SecurityGroupListResponse.  # noqa: E501
        :type security_groups: List[SecurityGroupResponse]
        """
        self.openapi_types = {
            'security_groups': List[SecurityGroupResponse]
        }

        self.attribute_map = {
            'security_groups': 'securityGroups'
        }

        self._security_groups = security_groups

    @classmethod
    def from_dict(cls, dikt) -> 'SecurityGroupListResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SecurityGroupListResponse of this SecurityGroupListResponse.  # noqa: E501
        :rtype: SecurityGroupListResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def security_groups(self):
        """Gets the security_groups of this SecurityGroupListResponse.


        :return: The security_groups of this SecurityGroupListResponse.
        :rtype: List[SecurityGroupResponse]
        """
        return self._security_groups

    @security_groups.setter
    def security_groups(self, security_groups):
        """Sets the security_groups of this SecurityGroupListResponse.


        :param security_groups: The security_groups of this SecurityGroupListResponse.
        :type security_groups: List[SecurityGroupResponse]
        """

        self._security_groups = security_groups
