# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest.models.security_group_bond import SecurityGroupBond
from rest import util

from rest.models.security_group_bond import SecurityGroupBond  # noqa: E501

class SecurityGroupBondsResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, hosts=None, subnets=None):  # noqa: E501
        """SecurityGroupBondsResponse - a model defined in OpenAPI

        :param hosts: The hosts of this SecurityGroupBondsResponse.  # noqa: E501
        :type hosts: List[SecurityGroupBond]
        :param subnets: The subnets of this SecurityGroupBondsResponse.  # noqa: E501
        :type subnets: List[SecurityGroupBond]
        """
        self.openapi_types = {
            'hosts': List[SecurityGroupBond],
            'subnets': List[SecurityGroupBond]
        }

        self.attribute_map = {
            'hosts': 'hosts',
            'subnets': 'subnets'
        }

        self._hosts = hosts
        self._subnets = subnets

    @classmethod
    def from_dict(cls, dikt) -> 'SecurityGroupBondsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SecurityGroupBondsResponse of this SecurityGroupBondsResponse.  # noqa: E501
        :rtype: SecurityGroupBondsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def hosts(self):
        """Gets the hosts of this SecurityGroupBondsResponse.


        :return: The hosts of this SecurityGroupBondsResponse.
        :rtype: List[SecurityGroupBond]
        """
        return self._hosts

    @hosts.setter
    def hosts(self, hosts):
        """Sets the hosts of this SecurityGroupBondsResponse.


        :param hosts: The hosts of this SecurityGroupBondsResponse.
        :type hosts: List[SecurityGroupBond]
        """

        self._hosts = hosts

    @property
    def subnets(self):
        """Gets the subnets of this SecurityGroupBondsResponse.


        :return: The subnets of this SecurityGroupBondsResponse.
        :rtype: List[SecurityGroupBond]
        """
        return self._subnets

    @subnets.setter
    def subnets(self, subnets):
        """Sets the subnets of this SecurityGroupBondsResponse.


        :param subnets: The subnets of this SecurityGroupBondsResponse.
        :type subnets: List[SecurityGroupBond]
        """

        self._subnets = subnets
