# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest import util


class SecurityGroupRuleDirection(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    UNKNOWN = "SGRD_UNKNOWN"
    INGRESS = "SGRD_INGRESS"
    EGRESS = "SGRD_EGRESS"
    def __init__(self):  # noqa: E501
        """SecurityGroupRuleDirection - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'SecurityGroupRuleDirection':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SecurityGroupRuleDirection of this SecurityGroupRuleDirection.  # noqa: E501
        :rtype: SecurityGroupRuleDirection
        """
        return util.deserialize_model(dikt, cls)
