# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest import util


class SecurityGroupBond(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, disabled=None):  # noqa: E501
        """SecurityGroupBond - a model defined in OpenAPI

        :param id: The id of this SecurityGroupBond.  # noqa: E501
        :type id: str
        :param name: The name of this SecurityGroupBond.  # noqa: E501
        :type name: str
        :param disabled: The disabled of this SecurityGroupBond.  # noqa: E501
        :type disabled: bool
        """
        self.openapi_types = {
            'id': str,
            'name': str,
            'disabled': bool
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'disabled': 'disabled'
        }

        self._id = id
        self._name = name
        self._disabled = disabled

    @classmethod
    def from_dict(cls, dikt) -> 'SecurityGroupBond':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SecurityGroupBond of this SecurityGroupBond.  # noqa: E501
        :rtype: SecurityGroupBond
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this SecurityGroupBond.


        :return: The id of this SecurityGroupBond.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SecurityGroupBond.


        :param id: The id of this SecurityGroupBond.
        :type id: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this SecurityGroupBond.


        :return: The name of this SecurityGroupBond.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SecurityGroupBond.


        :param name: The name of this SecurityGroupBond.
        :type name: str
        """

        self._name = name

    @property
    def disabled(self):
        """Gets the disabled of this SecurityGroupBond.


        :return: The disabled of this SecurityGroupBond.
        :rtype: bool
        """
        return self._disabled

    @disabled.setter
    def disabled(self, disabled):
        """Sets the disabled of this SecurityGroupBond.


        :param disabled: The disabled of this SecurityGroupBond.
        :type disabled: bool
        """

        self._disabled = disabled
