# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest.models.share_definition import ShareDefinition
from rest import util

from rest.models.share_definition import ShareDefinition  # noqa: E501

class ShareList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, share_list=None):  # noqa: E501
        """ShareList - a model defined in OpenAPI

        :param share_list: The share_list of this ShareList.  # noqa: E501
        :type share_list: List[ShareDefinition]
        """
        self.openapi_types = {
            'share_list': List[ShareDefinition]
        }

        self.attribute_map = {
            'share_list': 'shareList'
        }

        self._share_list = share_list

    @classmethod
    def from_dict(cls, dikt) -> 'ShareList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ShareList of this ShareList.  # noqa: E501
        :rtype: ShareList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def share_list(self):
        """Gets the share_list of this ShareList.


        :return: The share_list of this ShareList.
        :rtype: List[ShareDefinition]
        """
        return self._share_list

    @share_list.setter
    def share_list(self, share_list):
        """Sets the share_list of this ShareList.


        :param share_list: The share_list of this ShareList.
        :type share_list: List[ShareDefinition]
        """

        self._share_list = share_list
