# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest import util


class SshResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, output_std=None, output_err=None, status=None):  # noqa: E501
        """SshResponse - a model defined in OpenAPI

        :param output_std: The output_std of this SshResponse.  # noqa: E501
        :type output_std: str
        :param output_err: The output_err of this SshResponse.  # noqa: E501
        :type output_err: str
        :param status: The status of this SshResponse.  # noqa: E501
        :type status: int
        """
        self.openapi_types = {
            'output_std': str,
            'output_err': str,
            'status': int
        }

        self.attribute_map = {
            'output_std': 'outputStd',
            'output_err': 'outputErr',
            'status': 'status'
        }

        self._output_std = output_std
        self._output_err = output_err
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'SshResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SshResponse of this SshResponse.  # noqa: E501
        :rtype: SshResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def output_std(self):
        """Gets the output_std of this SshResponse.


        :return: The output_std of this SshResponse.
        :rtype: str
        """
        return self._output_std

    @output_std.setter
    def output_std(self, output_std):
        """Sets the output_std of this SshResponse.


        :param output_std: The output_std of this SshResponse.
        :type output_std: str
        """

        self._output_std = output_std

    @property
    def output_err(self):
        """Gets the output_err of this SshResponse.


        :return: The output_err of this SshResponse.
        :rtype: str
        """
        return self._output_err

    @output_err.setter
    def output_err(self, output_err):
        """Sets the output_err of this SshResponse.


        :param output_err: The output_err of this SshResponse.
        :type output_err: str
        """

        self._output_err = output_err

    @property
    def status(self):
        """Gets the status of this SshResponse.


        :return: The status of this SshResponse.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this SshResponse.


        :param status: The status of this SshResponse.
        :type status: int
        """

        self._status = status
