# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest import util


class SubnetState(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    UNKNOWNSTATE = "SS_UNKNOWNSTATE"
    PHASE1 = "SS_PHASE1"
    PHASE2 = "SS_PHASE2"
    READY = "SS_READY"
    NETWORKERROR = "SS_NETWORKERROR"
    def __init__(self):  # noqa: E501
        """SubnetState - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'SubnetState':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SubnetState of this SubnetState.  # noqa: E501
        :rtype: SubnetState
        """
        return util.deserialize_model(dikt, cls)
