# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest.models.subnet import Subnet
from rest import util

from rest.models.subnet import Subnet  # noqa: E501

class SubnetList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, subnets=None):  # noqa: E501
        """SubnetList - a model defined in OpenAPI

        :param subnets: The subnets of this SubnetList.  # noqa: E501
        :type subnets: List[Subnet]
        """
        self.openapi_types = {
            'subnets': List[Subnet]
        }

        self.attribute_map = {
            'subnets': 'subnets'
        }

        self._subnets = subnets

    @classmethod
    def from_dict(cls, dikt) -> 'SubnetList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SubnetList of this SubnetList.  # noqa: E501
        :rtype: SubnetList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def subnets(self):
        """Gets the subnets of this SubnetList.


        :return: The subnets of this SubnetList.
        :rtype: List[Subnet]
        """
        return self._subnets

    @subnets.setter
    def subnets(self, subnets):
        """Sets the subnets of this SubnetList.


        :param subnets: The subnets of this SubnetList.
        :type subnets: List[Subnet]
        """

        self._subnets = subnets
