# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest import util


class TenantName(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None):  # noqa: E501
        """TenantName - a model defined in OpenAPI

        :param name: The name of this TenantName.  # noqa: E501
        :type name: str
        """
        self.openapi_types = {
            'name': str
        }

        self.attribute_map = {
            'name': 'name'
        }

        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'TenantName':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TenantName of this TenantName.  # noqa: E501
        :rtype: TenantName
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this TenantName.


        :return: The name of this TenantName.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TenantName.


        :param name: The name of this TenantName.
        :type name: str
        """

        self._name = name
