# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest import util


class Tenant(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, provider=None):  # noqa: E501
        """Tenant - a model defined in OpenAPI

        :param name: The name of this Tenant.  # noqa: E501
        :type name: str
        :param provider: The provider of this Tenant.  # noqa: E501
        :type provider: str
        """
        self.openapi_types = {
            'name': str,
            'provider': str
        }

        self.attribute_map = {
            'name': 'name',
            'provider': 'provider'
        }

        self._name = name
        self._provider = provider

    @classmethod
    def from_dict(cls, dikt) -> 'Tenant':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Tenant of this Tenant.  # noqa: E501
        :rtype: Tenant
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this Tenant.


        :return: The name of this Tenant.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Tenant.


        :param name: The name of this Tenant.
        :type name: str
        """

        self._name = name

    @property
    def provider(self):
        """Gets the provider of this Tenant.


        :return: The provider of this Tenant.
        :rtype: str
        """
        return self._provider

    @provider.setter
    def provider(self, provider):
        """Sets the provider of this Tenant.


        :param provider: The provider of this Tenant.
        :type provider: str
        """

        self._provider = provider
