# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest.models.volume_inspect_response import VolumeInspectResponse
from rest import util

from rest.models.volume_inspect_response import VolumeInspectResponse  # noqa: E501

class VolumeListResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, volumes=None):  # noqa: E501
        """VolumeListResponse - a model defined in OpenAPI

        :param volumes: The volumes of this VolumeListResponse.  # noqa: E501
        :type volumes: List[VolumeInspectResponse]
        """
        self.openapi_types = {
            'volumes': List[VolumeInspectResponse]
        }

        self.attribute_map = {
            'volumes': 'volumes'
        }

        self._volumes = volumes

    @classmethod
    def from_dict(cls, dikt) -> 'VolumeListResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VolumeListResponse of this VolumeListResponse.  # noqa: E501
        :rtype: VolumeListResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def volumes(self):
        """Gets the volumes of this VolumeListResponse.


        :return: The volumes of this VolumeListResponse.
        :rtype: List[VolumeInspectResponse]
        """
        return self._volumes

    @volumes.setter
    def volumes(self, volumes):
        """Sets the volumes of this VolumeListResponse.


        :param volumes: The volumes of this VolumeListResponse.
        :type volumes: List[VolumeInspectResponse]
        """

        self._volumes = volumes
