# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest.models.base_model_ import Model
from rest import util


class VolumeSpeed(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    COLD = "VS_COLD"
    HDD = "VS_HDD"
    SSD = "VS_SSD"
    def __init__(self):  # noqa: E501
        """VolumeSpeed - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'VolumeSpeed':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VolumeSpeed of this VolumeSpeed.  # noqa: E501
        :rtype: VolumeSpeed
        """
        return util.deserialize_model(dikt, cls)
